#elasticsearch parameters
elasticsearch.host=localhost
elasticsearch.port=9200
#mongodb parameters
spring.data.mongodb.uri=mongodb://localhost:27017/JiraRepos
spring.data.mongodb.database=JiraRepos


#cors parameters
cors.allowedOrigins=http://localhost:4200
cors.allowedMethods=GET,POST,PUT,DELETE
cors.allowedHeaders=*
cors.allowCredentials=true


