
#milvus parameters
com.example.stacktradeapp.milvus.host=localhost
com.example.stacktradeapp.milvus.port=19530
com.example.stacktradeapp.milvus.summary.collection.name=spring_jira_summary_Collection
com.example.stacktradeapp.milvus.collections.id.field.name=ticket_id
com.example.stacktradeapp.milvus.summary.collection.vector.field.name=summary_vector
com.example.stacktradeapp.milvus.description.collection.name=spring_jira_description_Collection
com.example.stacktradeapp.milvus.description.collection.id.field.name=ticket_id
com.example.stacktradeapp.milvus.description.collection.vector.field.name=description_vector



#jwt config
application.security.jwt.secret-key=stacktradesecretkeyforjwttoken789987258852stacktradesecretkeyforjwttoken789987258852
application.security.jwt.expiration-ms=86400000
application.security.jwt.refresh-token.expiration-ms=604800000

#postgres config
spring.datasource.url=jdbc:postgresql://localhost:5432/ticket_app_database
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#ssl config
server.port=8443
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:stacktradekeystore.p12
server.ssl.key-store-password=mohamedamine
server.ssl.key-alias=stacktrade_ssl
server.ssl.enabled=true

#trust store location
trust.store=classpath:stacktradekeystore.p12
#trust store password
trust.store.password=mohamedamine

server.ssl.trust-all=true

#scheduling config
scheduling.enabled=true

