#elasticsearch parameters
elasticsearch.host=localhost
elasticsearch.port=9200
com.example.stacktradeapp.elasticsearch.indexName=spring_jira_index
#mongodb parameters
spring.data.mongodb.uri=mongodb://localhost:27017/JiraRepos
spring.data.mongodb.database=JiraRepos



#cors parameters
cors.allowedOrigins=http://localhost:4200
cors.allowedMethods=GET,POST,PUT,DELETE
cors.allowedHeaders=*
cors.allowCredentials=true

#milvus parameters
com.example.stacktradeapp.milvus.host=localhost
com.example.stacktradeapp.milvus.port=19530
com.example.stacktradeapp.milvus.description.vector.dimension=768
com.example.stacktradeapp.milvus.summary.vector.dimension=384
com.example.stacktradeapp.milvus.summary.collection.name=spring_jira_summary_Collection
com.example.stacktradeapp.milvus.summary.collection.VectorFieldName=summary_vector
com.example.stacktradeapp.milvus.description.collection.name=spring_jira_description_Collection
com.example.stacktradeapp.milvus.description.collection.VectorFieldName=description_vector
com.example.stacktradeapp.milvus.summary.description.id.name=ticket_id



